name: NPM package

on:
  push:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    uses: homebots/workflows/.github/workflows/node-build-release.yml@master
    with:
      registry: https://npm.pkg.github.com
    secrets:
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}